# Workflow name
name: Build

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build App
    environment: dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '^3.9'

      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: Code quality checks
        run: |
            source $VENV
            isort --check-only --profile black .
            black --check .
            flake8 --ignore D203 --exclude .venv,.git,__pycache__,docs/source/conf.py,old,build,dist --max-complexity 12 --max-line-length=88
            mypy src/*
            mypy tests/*

      - name: Run tests and coverage report
        run: |       
          coverage run --source=src --data-file tests/.coverage -m pytest -s
          coverage xml --data-file tests/.coverage -o tests/coverage.xml
          coverage report --data-file tests/.coverage -m
          
      - name : Send coverage report
        run: |
          pip install codacy-coverage
          export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
          export CODACY_API_TOKEN=${{ secrets.CODACY_API_TOKEN }}
          export CODACY_USERNAME=VSangarya
          export CODAY_PROJECT_NAME=AMATSA
          python-codacy-coverage -r tests/coverage.xml
